name: Release gem

on:
  repository_dispatch:
    types:
      - release-triggered
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4.10'
    - run: |
        gem install bundler -v 2.4
        bundle install
    - name: Test
      run: bundle exec rake

  release:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      gem_name: ${{ steps.release-gem.outputs.gem_name }}
      version: ${{ steps.release-gem.outputs.version }}
      increment: ${{ steps.release-gem.outputs.increment }}
    steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0
    - id: release-gem
      uses: pact-foundation/release-gem@v1
      env:
        GEM_HOST_API_KEY: '${{ secrets.RUBYGEMS_API_KEY }}'
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        INCREMENT: '${{ github.event.client_payload.increment }}'
